language: node_js
node_js:
- '10'
sudo: enabled
addons:
  ssh_known_hosts: 198.199.67.180
branches:
  only:
  - master
services:
- docker
env:
  global:
  - secure: W3VmODJRBcoPG3RnAPLkM8NBr6iFCOnWl2zYQguh5rwjy8zWtJuvJqt9LpdubgJi/yKcGAVpD5E67O0Y4OIfovWZbholHz+UzSSYQBGEV/ghF4WQqHG+LrP3wuIejUOyWW/WSJMzzpb9Cnm9lMdFIe6yll5nuAXkUNMFwG0syW/vYLuo2oD8QlhVmByKzDxUR7fAE+gvdOD+frSar9dSd9DiH6tuCMB7992gUEPyrxEkBcyl5ypTlfKh31jILnCp40QCpr85zSyVkfihengiTCBrnwFP+9PoFJHiF7r3R9+hfHPskrvtJf/A9XYrYpkYTRbwAN5+EXULjXiYsh6VWftkZsc40U+Ggb8x1hZIyElvC1/CZRfBkeVdUde3O+Zf0L62Kz8mrYZtIn0avBALtq+0NMCXhtMA1JIN89jfgaa54rHJEs/IcOzZOeHVHjQ+Ry1qc2mw1kZGLE5EW9DaGhm0ahIav7EO4cORsnA1rysEblvUJ4TlGMZhzbE29coKY48aiNvBcl83ZKUFk0+rqAuPYgAeIj4fM4kqJ+oXH+rgKZ3v/3pQ99HMN/VpJsQQZm87L+FMIxC++l56Yz5c+xzzqaRaQGYiY6ZKZTSqxUmuToZ5FRzMfU7kAhyVJvWxPUujTUQNmR9OT1YZeWm46I2YuugCBnN6p3IONmnBUd4=
  - DOCKER_USERNAME=dottjt
  - SERVER_IP_ADDRESS=198.199.67.180
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull dottjt/nfd-discord || true
script:
- ls -a
- echo "$AWS_ACCESS_KEY"
- docker-compose build nfd-discord
after_script:
- docker images
before_deploy:
- openssl aes-256-cbc -K $encrypted_7f67c5017926_key -iv $encrypted_7f67c5017926_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
deploy:
- provider: script
  script: docker push dottjt/nfd-discord
  on:
    branch: master
- provider: script
  script: bash deploy.sh
  on:
    branch: master
