version: '3'
services:
  nfd-discord:
    image: dottjt/nfd-discord
    container_name: 'nfd-discord'
    ports:
      - 2000:2000
      - 2001:2001
    build:
      context: .

    # networks:
    #   - docker-network
    # depends_on:
    #   - nfd-discord-postgres

  # nfd-discord-postgres:
  #   image: postgres:alpine
  #   container_name: 'nfd-discord-postgres'
  #   ports:
  #     - 5432:2345
  #   volumes:
  #     - ./nfd-discord-postgres:/var/lib/postgresql/data:rw
  #   restart: always
  #   env_file:
  #     - .env

# networks:
#   docker-network:
#     driver: bridge
